Repository ssaditya/Ecommute-SE_Project, pull requests merged in 2022-04, with the labels that each got.

#70 Handling CORS
  go.mod
  go.sum
  src/main/main.go
Labels: backend, api, sprint 3, difficulty 3

#76 Feature/frontend
  src/webapp/myreact/public/index.html
  src/webapp/myreact/src/App.css
  src/webapp/myreact/src/App.js
  src/webapp/myreact/src/components/DriverComponent.js
  src/webapp/myreact/src/components/DriverConfirmationComponent.js
  src/webapp/myreact/src/components/HeaderComponent.js
  src/webapp/myreact/src/components/HomeComponent.js
  src/webapp/myreact/src/components/LoginComponent.js
  src/webapp/myreact/src/components/MainComponent.js
  src/webapp/myreact/src/components/ResponsiveDrawer.js
  src/webapp/myreact/src/components/ResponsiveDrawerDriver.js
  src/webapp/myreact/src/components/RiderComponent.js
  src/webapp/myreact/src/components/RiderConfirmationComponent.js
  src/webapp/myreact/src/index.css
  src/webapp/myreact/src/shared/DropDown.js
  src/webapp/myreact/src/shared/Navbar.js
  src/webapp/myreact/src/shared/Time.js
  src/webapp/myreact/src/shared/modes.js
Labels: sprint 3

#77 Feature/sprint3/unit testing
  go.mod
  go.sum
  src/main/db_test.go
  src/main/trips_test.go
  src/main/users_test.go
Labels: backend, sprint 3, testing, difficulty 2

#80 Feature/frontend
  src/webapp/myreact/cypress.json
  src/webapp/myreact/cypress/fixtures/example.json
  src/webapp/myreact/cypress/integration/.2-advanced-examples/actions.spec.js
  src/webapp/myreact/cypress/integration/.2-advanced-examples/aliasing.spec.js
  src/webapp/myreact/cypress/integration/.2-advanced-examples/assertions.spec.js
  src/webapp/myreact/cypress/integration/.2-advanced-examples/connectors.spec.js
  src/webapp/myreact/cypress/integration/.2-advanced-examples/cookies.spec.js
  src/webapp/myreact/cypress/integration/.2-advanced-examples/cypress_api.spec.js
  src/webapp/myreact/cypress/integration/.2-advanced-examples/files.spec.js
  src/webapp/myreact/cypress/integration/.2-advanced-examples/local_storage.spec.js
  src/webapp/myreact/cypress/integration/.2-advanced-examples/location.spec.js
  src/webapp/myreact/cypress/integration/.2-advanced-examples/misc.spec.js
  src/webapp/myreact/cypress/integration/.2-advanced-examples/navigation.spec.js
  src/webapp/myreact/cypress/integration/.2-advanced-examples/network_requests.spec.js
  src/webapp/myreact/cypress/integration/.2-advanced-examples/querying.spec.js
  src/webapp/myreact/cypress/integration/.2-advanced-examples/spies_stubs_clocks.spec.js
  src/webapp/myreact/cypress/integration/.2-advanced-examples/traversal.spec.js
  src/webapp/myreact/cypress/integration/.2-advanced-examples/utilities.spec.js
  src/webapp/myreact/cypress/integration/.2-advanced-examples/viewport.spec.js
  src/webapp/myreact/cypress/integration/.2-advanced-examples/waiting.spec.js
  src/webapp/myreact/cypress/integration/.2-advanced-examples/window.spec.js
  src/webapp/myreact/cypress/integration/1-getting-started/todo.spec.js
  src/webapp/myreact/cypress/integration/driverconfirmation.js
  src/webapp/myreact/cypress/integration/driverpage.js
  src/webapp/myreact/cypress/integration/homepage.js
  src/webapp/myreact/cypress/integration/loginpage.js
  src/webapp/myreact/cypress/integration/riderconfirmation.js
  src/webapp/myreact/cypress/integration/riderpage.js
  src/webapp/myreact/cypress/plugins/index.js
  src/webapp/myreact/cypress/support/commands.js
  src/webapp/myreact/cypress/support/index.js
  src/webapp/myreact/package-lock.json
  src/webapp/myreact/package.json
  src/webapp/myreact/src/components/LoginComponent.js
Labels: frontend, sprint 3, testing, difficulty 2

#82 Unit Test for DeleteUser API
  src/main/users_test.go
Labels: backend, api, sprint 3, testing, difficulty 1

#83 Unit test for EditUserProfile API
  src/main/users_test.go
Labels: backend, api, sprint 3, testing, difficulty 2

#84 Fixing Bug in DeleteTrip API
  src/main/views/trip_handler.go
Labels: bug, backend, api, database, sprint 3, testing, difficulty 2

#98 Feature/sprint4 api
  src/main/main.go
  src/main/models/USERS.go
  src/main/views/user_handler.go
Labels: backend, api, sprint 4, difficulty 2

#99 Adding Logout with session logic
  src/main/main.go
  src/main/views/user_handler.go
Labels: backend, api, sprint 4, difficulty 1

#103 Fixing GetTrips API Bug
  src/main/main.go
  src/main/views/trip_handler.go
Labels: bug, backend, api, database, sprint 4, difficulty 2

#110 Bug Fix for DeleteTripMappingByRider API
  src/main/main.go
  src/main/views/trip_mapping_handler.go
Labels: bug, backend, api, database, sprint 4, difficulty 2

#112 Delete APIs Bugfix
  src/main/main.go
  src/main/views/trip_handler.go
  src/main/views/user_handler.go
Labels: bug, backend, api, database, sprint 4, difficulty 1

#114 Unit Testing - Login flow
  src/main/users_test.go
Labels: backend, api, sprint 4, testing, difficulty 1

#117 Unit Test - GetUserByUsername API
  src/main/db_test.go
  src/main/users_test.go
Labels: backend, api, sprint 4, testing, difficulty 1

#125 Bug Fix for Date Values
  src/main/db_test.go
Labels: bug, backend, api, sprint 4, difficulty 1

#126 Unit Test for GetTrips API
  src/main/trips_test.go
  src/main/views/trip_handler.go
Labels: backend, api, sprint 4, testing, difficulty 1

#127 Unit Test for EditTrip API
  src/main/trips_test.go
  src/main/views/trip_handler.go
Labels: backend, api, sprint 4, testing, difficulty 1

#128 Unit Test for CreateTrip API
  src/main/trips_test.go
Labels: backend, api, sprint 4, testing, difficulty 1

#134 Unit Test for CreatePastTrip
  src/main/db_test.go
  src/main/test.db
  src/main/trips_test.go
Labels: backend, api, sprint 4, testing, difficulty 1

#136 Unit Test for GetPastTripById
  src/main/test.db
  src/main/trips_test.go
Labels: backend, api, sprint 4, testing, difficulty 1

#137 Unit Test for GetDriverUpcomingTrips
  src/main/test.db
  src/main/trips_test.go
Labels: backend, api, sprint 4, testing, difficulty 1

#138 Unit Test for GetRiderUpcomingTrips
  src/main/test.db
  src/main/trips_test.go
Labels: backend, api, sprint 4, testing, difficulty 1

#139 Unit Test for DeleteTripMappingByDriver
  src/main/test.db
  src/main/trips_test.go
Labels: backend, api, sprint 4, testing, difficulty 1

#145 Added Unit Test TestDeleteTripMappingByRider
  src/main/test.db
  src/main/trips_test.go
Labels: backend, api, sprint 4, testing

#147 Bug Fix and Test Case for Delete API
  src/main/db_test.go
  src/main/trips_test.go
  src/main/views/trip_mapping_handler.go
Labels: bug, backend, api, database, sprint 4, testing, difficulty 2
